### ISSUE TITLE
class ImportAllAction not found

### ISSUE THREAD

**Issue by abd3lraouf** [Guichaguri/AdditionalTools#1]
PluginException: class with name "me.guichaguri.additionaltools.ImportAll.ImportAllAction" not found [Plugin: me.guichaguri.additionaltools]

I 've just installed the plugin, my intelljidea version is : 
![screenshot 1](https://cloud.githubusercontent.com/assets/11881564/10120689/e2d920fa-64c8-11e5-9654-d0f96ec6d040.png)

**Comment by Guichaguri** [comment]
Thanks for reporting, that was my dumb mistake. Fixed in 6f7e09c
I just uploaded a new version, it might take a few days to get approved.

**Comment by abd3lraouf** [comment]
Thanks @Guichaguri for your help. #Nice tool

**Comment by Guichaguri** [comment]
Thanks! It's really nice to hear that. I just wanted more features, but I can't think of anything good at all =P

**Comment by abd3lraouf** [comment]
I promise that if I had any, you would be the first to know ;)
